language: php
php:
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly

before_script:
  - sudo apt-get update
  - sudo apt-get install memcached php-memcached
  - sudo pecl install apcu
  - composer install
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini