dist: trusty
sudo: false
language: php

cache:
    directories:
        - $HOME/.composer/cache
php:
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly

services:
  - memcached


before_install:
    - pecl channel-update pecl.php.net
    - pecl config-set preferred_state beta
    - echo yes | pecl upgrade apcu

install:
    - travis_retry composer update --no-interaction --prefer-dist